import { Poppins } from 'next/font/google'
import "./globals.css";
import Navbar from "@/_components/Navbar";
import Footer from "@/_components/Footer";
import { ThemeProvider } from 'next-themes';


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // add weights you need
  display: 'swap',
  variable: '--font-poppins', // optional, for Tailwind use
})

export const metadata = {
  title: "Nidhi Patel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={poppins.className}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar/>
          <div className="w-full md:w-[65%] mx-auto">
            {children}
          </div>
            <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
